# server port
server:
  port: 9090

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_codingrecipe
    password: han18712!

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml